import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Todo from "../src/component/Todo";
import Layout from "../src/component/Layout";
import Register from "./register";
export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if (!localStorage.getItem("user")) {
      router.push("/register");
      return;
    }
    const authData = JSON.parse(localStorage.getItem("user"));
    if (authData.isLogout) {
      router.push("/login");
    }
  }, [router]);

  return (
    <div>
      <Head>
        <title>Ahamove | Coding interview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./icons/BrandingLogomoi-01.png" />
      </Head>

      {typeof window !== "undefined" && localStorage.getItem("user") ? (
        <Layout>
          <Todo />
        </Layout>
      ) : (
        <Register />
      )}
    </div>
  );
}
